POST http://localhost:5000/graphql
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQiLCJuYW1lIjoiYXN0cm9uYXV0IiwiaWF0IjoxNTQyODk0NjcwLCJleHAiOjE1NDI5ODEwNzB9.kENhcY0wxCRM8-NwSuGSGjzOEYTzaI4eTmk7k0wGFxc

{"query":"query me {me{id, name}}"}

---

POST http://localhost:5000/graphql
Content-type: application/json
Accept: application/json

{
  "query":"mutation login($name: String!, $password: String!) {login(name: $name, password:$password)}",
  "variables":{"name":"astronaut","password":"universe"}
}

---

POST http://localhost:5000/graphql
Content-type: application/json

{"query":"{lastUpdated}"}

---

POST http://localhost:5000/graphql
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQiLCJuYW1lIjoiYXN0cm9uYXV0IiwiaWF0IjoxNTQyODk0NjcwLCJleHAiOjE1NDI5ODEwNzB9.kENhcY0wxCRM8-NwSuGSGjzOEYTzaI4eTmk7k0wGFxc

{"query":"{lastUpdated}"}

---

POST http://localhost:5000/graphql
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQiLCJuYW1lIjoiYXN0cm9uYXV0IiwiaWF0IjoxNTQyODk0NjcwLCJleHAiOjE1NDI5ODEwNzB9.kENhcY0wxCRM8-NwSuGSGjzOEYTzaI4eTmk7k0wGFxc

{
  "query":"mutation addAstronaut($firstName: String!, $lastName: String!, $birth: String!, $superpower: String!) {\n      addAstronaut(firstName: $firstName, lastName: $lastName, birth: $birth, superpower: $superpower) {\n        id\n        firstName\n        lastName\n        birth\n        superpower\n      }\n    }", "variables":{
    "firstName": "Neil",
    "lastName": "Armstrong",
    "birth": "1930-08-05",
    "superpower": "healing"
  }
}

---

POST http://localhost:5000/graphql
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQiLCJuYW1lIjoiYXN0cm9uYXV0IiwiaWF0IjoxNTQyODk0NjcwLCJleHAiOjE1NDI5ODEwNzB9.kENhcY0wxCRM8-NwSuGSGjzOEYTzaI4eTmk7k0wGFxc

{
  "query":"query astronaut($id: String!) {\n  astronaut(id: $id) {\n    id\n    firstName\n    lastName\n    birth\n    superpower\n  }\n}",
"variables":{"id":"5b8c26c31254491899fa7545"}
}

---

POST http://localhost:5000/graphql
Content-type: application/json

{
  "query":"query astronaut($id: String!) {\n  astronaut(id: $id) {\n    id\n    firstName\n    lastName\n    birth\n    superpower\n  }\n}",
"variables":{"id":"5b8c26c31254491899fa7545"}
}

---

GET http://localhost:5000/

---
